name: Discord Webhook

on:
  push:
    branches:
      - '**'

jobs:
  discord_webhook:
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy Success
        uses: rjstone/discord-webhook-notify@v1.0.0
        if: success()
        with:
          severity: info
          details: Deploy Succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
